python train.py --agent=PyDQN --folder=./tests/pydqn/1
python train.py --agent=PyDQN --folder=./tests/pydqn/2
python train.py --agent=PyDQN --folder=./tests/pydqn/3
python train.py --agent=PyTEDQN --folder=./tests/pyteqn/1
python train.py --agent=PyTEDQN --folder=./tests/pytedqn/2
python train.py --agent=PyTEDQN --folder=./tests/pytedqn/3
python train.py --agent=PG --folder=./tests/pg/1
python train.py --agent=PG --folder=./tests/pg/2
python train.py --agent=PG --folder=./tests/pg/3
python train.py --agent=PFRLDQN --folder=./tests/pfrldqn/1
python train.py --agent=PFRLDQN --folder=./tests/pfrldqn/2
python train.py --agent=PFRLDQN --folder=./tests/pfrldqn/3
